config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "dictionary", to: "pages#dictionary", as: "dictionary"
  get "create_words", to: "pages#create_words", as: "create_words"

  get 'institucional', to: 'pages#institucional'
  get 'calidad', to: 'pages#calidad'
  get 'contacto', to: 'pages#contacto'
  get 'medio_ambiente', to: 'pages#medio_ambiente'
  get 'trabaja_con_nosotros', to: 'pages#trabaja_con_nosotros'
  get 'que_hacemos', to: 'pages#que_hacemos'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
  validates :word, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:dictionary, :create_words, :home, :contacto, :calidad, :institucional, :medio_ambiente, :que_hacemos, :trabaja_con_nosotros]

  def home; end

  def dictionary
    @words = Dictionary.all
  end
  def create_words
    # alphanum = (33..126).map &:chr
    alphanum = [*?a..?z, *?A..?Z, *?0..?9]
    dictionary = 3.times.flat_map { |l|
      alphanum.repeated_permutation(l + 1).map(&:join)
    }
    dictionary.uniq.each do |word|
      Dictionary.create(word: word)
    end

    redirect_to dictionary_path

  end

  def contacto; end
  def institucional; end
  def medio_ambiente; end
  def que_hacemos; end
  def trabaja_con_nosotros; end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calidad/index.html.erb
<div class="container">
	<h1>hello world</h1>
	<h1 class="">This is the "Calidad" view</h1>
</div>

app/views/contacto/index.html.erb
<div class="container">
  <h1>hello world</h1>
  <h1 class="">This is the "Contacto" view</h1>
</div>

app/views/institucional/index.html.erb
<div class="container">
  <h1>hello world</h1>
  <h1 class="">This is the "Institucional" view</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>TODO</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
  <script src='https://api.mapbox.com/mapbox.js/v3.2.0/mapbox.js'></script>
  <link href='https://api.mapbox.com/mapbox.js/v3.2.0/mapbox.css' rel='stylesheet' />



  <link href="https://fonts.googleapis.com/css?family=Satisfy&display=swap" rel="stylesheet">
</head>
<body>
  <%= render 'shared/navbar' %>

  <% if controller_name = 'pages' && action_name != 'home' %>
  <div class="invisible-navbar" style="height: 100px;"></div>
  <% end %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= render 'shared/footer' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/medio_ambiente/index.html.erb
<div class="container">
  <h1>hello world</h1>
  <h1 class="">This is the "Medio Ambiente" view</h1>
</div>

app/views/pages/calidad.html.erb
<div class="container">
	<h1>hello world</h1>
	<h1 class="">This is the "Calidad" view</h1>
</div>

app/views/pages/contacto.html.erb
<div class="container">
  <h1>hello world</h1>
  <h1 class="">This is the "Contacto" view</h1>
</div>

app/views/pages/dictionary.html.erb
<h1>HELLO WORLD</h1>

<a href="/dictionary">REFRESH</a>
<%= link_to "create_words", create_words_path %>
<br>
<%= @words.count %>
<ol>
  <% @words.each do |word| %>
    <li>length: <%= word.word.length %> word: <%= word.word %></li>
  <% end %>
</ol>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<div class="py-1rounded-lg" style="padding: 50px; background-image: linear-gradient(to right, rgba(19, 91, 191, 0.1), rgba(17, 63, 128,1));">
  <div class="container text-center align-items-center">
    <h4>BIENVENIDO A LAUSOL S.A.</h4>
    <h1>UNA EMPRESA SOCIALMENTE RESPONSABLE</h1>
  </div>
</div>
<%= render 'pages/partials/services_with_icons' %>


<div style="background-image: url('https://www.usnews.com/dims4/USNEWS/d07813a/2147483647/thumbnail/640x420/quality/85/?url=http%3A%2F%2Fcom-usnews-beam-media.s3.amazonaws.com%2Fe4%2Fd5%2F43a0ac914af7abefa6704b41eb54%2F160307-cleaningservices-stock.jpg'); height:40vh; background-size: cover; background-repeat: no-repeat; background-attachment: fixed; background-position: center; position: relative';">
  <div class="background-opacity" style="background-color: rgba(0,0,0,0.7); height: 40vh">
    <div class="row text-center d-flex justify-content-center align-items-center" style="margin: 0;">
      <div class="col-lg-6 col-xs-12 text-opacity service-banner" style="padding: 4% 10%;">
          <h1 style="color: white; text-shadow: 2px 2px 2px rgba(0,0,0,0.5);"><strong>NUESTROS SERVICIOS</strong></h1>
          <h3 style="color: white; text-shadow: 2px 2px 2px rgba(0,0,0,0.5);"><strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt atque, harum facilis</strong></h3>
      </div>
    </div>
  </div>
  <br><br><br>
  <div style="background-image: url('https://www.usnews.com/dims4/USNEWS/d07813a/2147483647/thumbnail/640x420/quality/85/?url=http%3A%2F%2Fcom-usnews-beam-media.s3.amazonaws.com%2Fe4%2Fd5%2F43a0ac914af7abefa6704b41eb54%2F160307-cleaningservices-stock.jpg'); height:40vh; background-size: cover; background-repeat: no-repeat; background-attachment: fixed; background-position: center; position: relative';">
    <div class="background-opacity" style="background-color: rgba(0,121,193,0.9); height: 40vh">
      <div class="row text-center d-flex justify-content-center align-items-center" style="margin: 0;">
        <div class="col-lg-6 col-xs-12 text-opacity service-banner" style="padding: 4% 10%;">
          <h1 style="color: white; text-shadow: 2px 2px 2px rgba(0,0,0,0.5);"><strong>NUESTROS SERVICIOS</strong></h1>
          <h3 style="color: white; text-shadow: 2px 2px 2px rgba(0,0,0,0.5);"><strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt atque, harum facilis</strong></h3>
        </div>
      </div>
    </div>
  </div>

  <br><br><br>
  <div style="background-image: url('https://www.usnews.com/dims4/USNEWS/d07813a/2147483647/thumbnail/640x420/quality/85/?url=http%3A%2F%2Fcom-usnews-beam-media.s3.amazonaws.com%2Fe4%2Fd5%2F43a0ac914af7abefa6704b41eb54%2F160307-cleaningservices-stock.jpg'); height:40vh; background-size: cover; background-repeat: no-repeat; background-attachment: fixed; background-position: center; position: relative';">
    <div class="background-opacity" style="background-color: rgba(21,46,71,0.9); height: 40vh">
      <div class="row text-center d-flex justify-content-center align-items-center" style="margin: 0;">
        <div class="col-lg-6 col-xs-12 text-opacity service-banner" style="padding: 4% 10%;">
          <h1 style="color: white; text-shadow: 2px 2px 2px rgba(0,0,0,0.5);"><strong>NUESTROS SERVICIOS</strong></h1>
          <h3 style="color: white; text-shadow: 2px 2px 2px rgba(0,0,0,0.5);"><strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt atque, harum facilis</strong></h3>
        </div>
      </div>
    </div>
  </div>
  <br><br><br>
  <div style="background-image: url('https://www.usnews.com/dims4/USNEWS/d07813a/2147483647/thumbnail/640x420/quality/85/?url=http%3A%2F%2Fcom-usnews-beam-media.s3.amazonaws.com%2Fe4%2Fd5%2F43a0ac914af7abefa6704b41eb54%2F160307-cleaningservices-stock.jpg'); height:40vh; background-size: cover; background-repeat: no-repeat; background-attachment: fixed; background-position: center; position: relative';">
    <div class="row text-center d-flex justify-content-center align-items-center" style="margin: 0;">
      <div class="col-lg-6 col-xs-12 text-opacity service-banner" style="padding: 4% 10%;">
        <h1 style="color: white; text-shadow: 2px 2px 2px rgba(0,0,0,0.5);"><strong>NUESTROS SERVICIOS</strong></h1>
        <h3 style="color: white; text-shadow: 2px 2px 2px rgba(0,0,0,0.5);"><strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt atque, harum facilis</strong></h3>
      </div>
    </div>
  </div>
  <br><br><br>


  <%= render 'pages/partials/services_cards' %>
  <br><br><br>
  <%= render 'pages/partials/our_services' %>

  <br><br><br>

  <%= render 'pages/partials/services_banner' %>


  <br><br><br>

  <!-- cards -->
  <div class="container">
    <div class="row justify-content-center">
      <div class="description-card col-lg-3 col-sm-12 col-md-12 col-xs-12 text-center" style="width: 15rem;">
        <div class="">
          <img src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/plan-negocio-empresa-limpieza-1546535118.jpg?crop=1.00xw:0.847xh;0,0.106xh&resize=480:*" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
      <div class="description-card col-lg-3 col-sm-12 col-md-12 col-xs-12 text-center" style="width: 15rem;">
        <div class="">
          <img src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/plan-negocio-empresa-limpieza-1546535118.jpg?crop=1.00xw:0.847xh;0,0.106xh&resize=480:*" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
      <div class="description-card col-lg-3 col-sm-12 col-md-12 col-xs-12 text-center" style="width: 15rem;">
        <div class="">
          <img src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/plan-negocio-empresa-limpieza-1546535118.jpg?crop=1.00xw:0.847xh;0,0.106xh&resize=480:*" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
      <div class="description-card col-lg-3 col-sm-12 col-md-12 col-xs-12 text-center" style="width: 15rem;">
        <div class="">
          <img src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/plan-negocio-empresa-limpieza-1546535118.jpg?crop=1.00xw:0.847xh;0,0.106xh&resize=480:*" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/pages/institucional.html.erb
<div class="container">

  <h1 class="">This is the "Institucional" view</h1>
</div>

app/views/pages/medio_ambiente.html.erb
<div class="container">
  <h1>hello world</h1>
  <h1 class="">cambio view</h1>
</div>

app/views/pages/partials/_carrousel.html.erb
<!-- <div class="carrousel-brands">
  <div class="container">
   <div class="row center">
     <div class="col-md-12">
      <h2>Algunas marcas con las que hemos trabajado</h2>
    </div>
  </div>
  <div class="row center">
   <div class="owl-carousel carrousel-brands">
    <div>
      <%= image_tag "https://s3-sa-east-1.amazonaws.com/bierful/images/logos/schaferhund.png", class: "img-responsive" %>
    </div>
    <div>
      <%= image_tag "https://s3-sa-east-1.amazonaws.com/bierful/images/logos/btn_darwin.png", class: "img-responsive" %>
    </div>
    <div>
      <%= image_tag "https://s3-sa-east-1.amazonaws.com/bierful/images/logos/letzen.png", class: "img-responsive" %>
    </div>
    <div>
      <%= image_tag "https://s3-sa-east-1.amazonaws.com/bierful/images/logos/uelts.png", class: "img-responsive" %>
    </div>
    <div>
      <%= image_tag "https://s3-sa-east-1.amazonaws.com/bierful/images/logos/postanak.png", class: "img-responsive" %>
    </div>
    <div>
      <%= image_tag "https://s3-sa-east-1.amazonaws.com/bierful/images/logos/westen.png", class: "img-responsive" %>
    </div>
    <div>
      <%= image_tag "https://s3-sa-east-1.amazonaws.com/bierful/images/logos/baronesa.png", class: "img-responsive" %>
    </div>
    <div>
      <%= image_tag "https://s3-sa-east-1.amazonaws.com/bierful/images/logos/wallem.png", class: "img-responsive" %>
    </div>
    <div>
      <%= image_tag "https://s3-sa-east-1.amazonaws.com/bierful/images/logos/tiwaz.png", class: "img-responsive" %>
    </div>
    <div>
      <%= image_tag "https://s3-sa-east-1.amazonaws.com/bierful/images/logos/brujas.png", class: "img-responsive" %>
    </div>
    <div>
      <%= image_tag "https://s3-sa-east-1.amazonaws.com/bierful/images/logos/penon_del_aguila.png", class: "img-responsive" %>
    </div>
    <div>
      <%= image_tag "https://s3-sa-east-1.amazonaws.com/bierful/images/logos/berkeler.png", class: "img-responsive" %>
    </div>
    <div>
      <%= image_tag "https://s3-sa-east-1.amazonaws.com/bierful/images/logos/cruz_diablo.png", class: "img-responsive" %>
    </div>
  </div>
</div>
</div>
</div>
 -->

app/views/pages/partials/_our_services.html.erb
<div class="container">
<h1 class="text-center">Nuestros servicios</h1>
  <div class="row justify-content-center services-row">
    <div>
      <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
        <div class="card service-card py-4 my-4" style="width: 18rem;">
          <div class="card-icon d-flex justify-content-center">
            <i class="fas fa-broom" style="font-size: 100px; padding: 25px; border-style: solid; border-width: 10px; border-color: rgb(75, 198, 137); border-radius: 50%"></i>
          </div>
          <div class="card-body text-center">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
    </div>
    <div>

      <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
        <div class="card service-card py-4 my-4" style="width: 18rem;">
          <div class="card-icon d-flex justify-content-center">
            <i class="fas fa-broom" style="font-size: 100px; padding: 25px; border-style: solid; border-width: 10px; border-color: rgb(75, 198, 137); border-radius: 50%"></i>
          </div>
          <div class="card-body text-center">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
    </div>
    <div>
      <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
        <div class="card service-card py-4 my-4" style="width: 18rem;">
          <div class="card-icon d-flex justify-content-center">
            <i class="fas fa-broom" style="font-size: 100px; padding: 25px; border-style: solid; border-width: 10px; border-color: rgb(75, 198, 137); border-radius: 50%"></i>
          </div>
          <div class="card-body text-center">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
    </div>
    <div>
      <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
        <div class="card service-card py-4 my-4" style="width: 18rem;">
          <div class="card-icon d-flex justify-content-center">
            <i class="fas fa-broom" style="font-size: 100px; padding: 25px; border-style: solid; border-width: 10px; border-color: rgb(75, 198, 137); border-radius: 50%"></i>
          </div>
          <div class="card-body text-center">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
    </div>
    <div>
      <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
        <div class="card service-card py-4 my-4" style="width: 18rem;">
          <div class="card-icon d-flex justify-content-center">
            <i class="fas fa-broom" style="font-size: 100px; padding: 25px; border-style: solid; border-width: 10px; border-color: rgb(75, 198, 137); border-radius: 50%"></i>
          </div>
          <div class="card-body text-center">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
    </div>
    <div>
      <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
        <div class="card service-card py-4 my-4" style="width: 18rem;">
          <div class="card-icon d-flex justify-content-center">
            <i class="fas fa-broom" style="font-size: 100px; padding: 25px; border-style: solid; border-width: 10px; border-color: rgb(75, 198, 137); border-radius: 50%"></i>
          </div>
          <div class="card-body text-center">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/pages/partials/_services_banner.html.erb
<div class="container-fluid" style="background-color: #004166;">
  <div class="row text-center d-flex justify-content-center align-items-center">
    <div class="col-lg-6 col-xs-12" style="padding: 10px 10%;">
      <h1 style="color: white">NUESTROS SERVICIOS</h1>
      <p style="color: white">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt atque, harum facilis officiis quasi temporibus. Sapiente fuga, illum labore dolor saepe, nobis ipsam nam consectetur. Aut dolorum provident officia odit.</p>
    </div>
    <div class="col-lg-6 col-xs-12" style="margin: 0; padding: 0">
      <img src="https://s04.s3c.es/imag/_v0/770x420/1/5/9/700x420_empleada-limpieza-hogar-dreams.jpg" alt="" class="normas-iso" style="width: 100%; height: 500px;">
    </div>
  </div>
</div>

app/views/pages/partials/_services_cards.html.erb
<div class="container">
  <div class="row">
    <div class="presentation-card col-lg-4 col-xs-12 p-4">
      <div class="presentation-img">
        <img src="https://mecaluxar.cdnwm.com/casos-practicos/frio-dock-deposito-frio-argentina.1.7.jpg" alt="">
        <div class="presentation-content col-12">
          <a href="#" class="presentation-title">Titulo</a>
          <div class="presentation-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore hic autem repudiandae adipisci, natus dolor tenetur quasi quisquam reiciendis quos animi dolore! Incidunt ratione deleniti quasi autem excepturi dolor ullam.
          </div>
          <div class="presentation-more-info button">
            <a href="#">Read more...</a>
          </div>
        </div>
      </div>
    </div>
    <div class="presentation-card col-lg-4 col-xs-12 p-4">
      <div class="presentation-img">
        <img src="https://mecaluxar.cdnwm.com/casos-practicos/frio-dock-deposito-frio-argentina.1.7.jpg" alt="">
        <div class="presentation-content col-12">
          <a href="#" class="presentation-title">Titulo</a>
          <div class="presentation-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore hic autem repudiandae adipisci, natus dolor tenetur quasi quisquam reiciendis quos animi dolore! Incidunt ratione deleniti quasi autem excepturi dolor ullam.
          </div>
          <div class="presentation-more-info button">
            <a href="#">Read more...</a>
          </div>
        </div>
      </div>
    </div>
    <div class="presentation-card col-lg-4 col-xs-12 p-4">
      <div class="presentation-img">
        <img src="https://mecaluxar.cdnwm.com/casos-practicos/frio-dock-deposito-frio-argentina.1.7.jpg" alt="">
        <div class="presentation-content col-12">
          <a href="#" class="presentation-title">Titulo</a>
          <div class="presentation-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore hic autem repudiandae adipisci, natus dolor tenetur quasi quisquam reiciendis quos animi dolore! Incidunt ratione deleniti quasi autem excepturi dolor ullam.
          </div>
          <div class="presentation-more-info button">
            <a href="#">Read more...</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/partials/_services_with_icons.html.erb
<div class="container">
  <h1 class="text-center">Nuestros servicios</h1>
  <div class="row justify-content-center services-row">


    <div class="col-lg-3 col-xl-3 col-md-6 col-sm-12 col-xs-12 p-4">
      <div class="service-card py-4" style="width: 18rem; ; margin: auto;">
        <div class="card-icon d-flex justify-content-center">
          <i class="fas fa-trash" style="font-size: 70px; padding: 25px; background-color: rgba(25, 189, 68); border-radius: 50%; color: white"></i>
        </div>
        <div class="card-body text-center">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-xl-3 col-md-6 col-sm-12 col-xs-12 p-4">
      <div class="service-card py-4" style="width: 18rem; ; margin: auto;">
        <div class="card-icon d-flex justify-content-center">
          <i class="fas fa-broom" style="font-size: 70px; padding: 25px; background-color: rgba(25, 186, 189); border-radius: 25%; color: white"></i>
        </div>
        <div class="card-body text-center">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-xl-3 col-md-6 col-sm-12 col-xs-12 p-4">
      <div class="service-card py-4" style="width: 18rem; ; margin: auto;">
        <div class="card-icon d-flex justify-content-center">
          <i class="fas fa-truck" style="font-size: 70px; padding: 25px; background-color: rgba(59, 78, 173); border-radius: 10%; color: white"></i>
        </div>
        <div class="card-body text-center">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-xl-3 col-md-6 col-sm-12 col-xs-12 p-4">
      <div class="service-card py-4" style="width: 18rem; ; margin: auto;">
        <div class="card-icon d-flex justify-content-center">
          <i class="fas fa-envelope" style="font-size: 70px; padding: 25px; background-color: #134181; border-radius: 50%; color: white"></i>
        </div>
        <div class="card-body text-center">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/que_hacemos.html.erb
<div class="container">
  <h1>hello world</h1>
  <h1 class="">This is the "Que hacemos asdf" view</h1>
</div>

app/views/shared/_navbar.html.erb
<nav id="navbar-lausol" class="navbar navbar-expand-lg d-flex navbar-light justify-content-between bg-white pt-3 fixed-top <%= controller_name == 'pages' && action_name == 'home' ? 'navbar-lausol' : "navbar-lausol-white " %>" style="">

<!--   <a href="/"><img src="http://www.cleanmanagers.com/images/logo.png" class="lausol-logo" alt="" style="margin-left: 100px"></a>
 -->

  <div class="nav-info" style="margin-right: 100px">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse font-weight-bold" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "INSTITUCIONAL", institucional_path, class:"nav-link mx-1 border-left border-primary" %>
        </li>
        <li class="nav-item">
          <%= link_to "CALIDAD", calidad_path, class:"nav-link mx-1 border-left border-primary" %>
        </li>
        <li class="nav-item">
          <%= link_to "MEDIO AMBIENTE", medio_ambiente_path, class:"nav-link mx-1 border-left border-primary" %>
        </li>
        <li class="nav-item">
          <%= link_to "TRABAJA CON NOSOTROS", trabaja_con_nosotros_path, class:"nav-link mx-1 border-left border-primary" %>
        </li>
        <li class="nav-item">
          <%= link_to "QUE HACEMOS", que_hacemos_path, class:"nav-link mx-1 border-left border-primary" %>
        </li>
        <li class="nav-item">
          <%= link_to "CONTACTO", contacto_path, class:"nav-link mx-1 border-left border-primary" %>
        </li>
        <li class="nav-item">
          <% if current_user == nil %>
          <%= link_to "LOGIN", new_user_session_path, class:"nav-link mx-1 border-left border-primary" %>
          <% else %>
          <%= link_to "Log Out", destroy_user_session_path(:authenticity_token => form_authenticity_token()), method: :delete, class:"nav-link mx-1 border-left border-primary" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>